name: CI

on:
  push:
    branches: [main]

jobs:
  lint_and_format:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Check format
        run: npm run format:check

      - name: Check linter
        run: npm run lint:check
